name: Build, Test, and Release Minecraft Mod

on:
  push:
    branches:
      - main  # 在推送到 main 分支时触发构建和测试，作为 CI 备选
  release:
    types: [created]  # 在创建 Release 时触发完整流程

permissions:
  contents: write  # 明确授予写入权限，用于创建或更新 Release

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # 运行环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # 根据您的需求调整 Java 版本
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests with Gradle
        run: ./gradlew test  # 运行测试步骤

      - name: Build with Gradle
        run: ./gradlew build  # 运行构建步骤

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4  # 使用 actions/upload-artifact 上传文件
        with:
          name: build-libs  # 工件名称，可以自定义
          path: build/libs/  # 上传 build/libs 目录
          retention-days: 1  # 保留时间，仅需临时使用

  upload-assets:
    runs-on: ubuntu-latest  # 运行环境
    needs: build-and-test  # 依赖于 build-and-test 作业成功后运行
    if: github.event_name == 'release' && github.event.action == 'created'  # 仅在 release.created 事件时运行

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 重新检出代码

      - name: Download built artifacts
        uses: actions/download-artifact@v4  # 下载工件
        with:
          name: build-libs  # 与上传时匹配的工件名称
          path: build/libs/  # 下载到 build/libs 目录

      - name: Debug event and tag info
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Release Tag: ${{ github.event.release.tag_name }}"
          echo "GitHub Ref: ${{ github.ref }}"

      - name: Find the main JAR file dynamically
        id: find_jar
        run: |
          # 现在 build/libs 目录应该已经下载好了
          JAR_FILE=$(find build/libs -type f -name "testmoddevelop-*.jar" ! -name "*sources.jar" | head -n 1)
          if [ -z "$JAR_FILE" ]; then
            echo "No matching JAR file found!" >&2
            exit 1  # 如果未找到文件，退出并失败
          fi
          echo "Found JAR: $JAR_FILE"
          echo "::set-output name=jar_path::$JAR_FILE"  # 输出路径

      - name: Upload the JAR file to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.find_jar.outputs.jar_path }}  # 使用动态路径上传文件
          tag_name: ${{ github.event.release.tag_name }}  # 使用 release 事件的标签名称
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用默认令牌
